### ISSUE TITLE
Apple LLVM 6.0 Error due to cordova device plugin

### ISSUE THREAD

**Issue by prabjeetpahwa** [tbago/base#2]
Hi,
I installed the cordova device plugin for iOS to my project, but as soon as I build the project it gives me a Apple LLVM 6.0 Error.

Under Compile CDVDevice.m I get this description:

CompileC DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/Objects-normal/armv7/CDVDevice.o mpesaCustomer/Plugins/cordova-plugin-device/CDVDevice.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/mac358818/vodafoneMpesaCustomer/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode 3.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode\ 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode\ 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/mpesaCustomer-generated-files.hmap -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/mpesaCustomer-own-target-headers.hmap -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/mpesaCustomer-all-target-headers.hmap -iquote /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/mpesaCustomer-project-headers.hmap -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Products/Debug-iphoneos/include -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Products/Debug-iphoneos/usr/local/lib/include -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/UninstalledProducts/include -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Products/Debug-iphoneos -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/DerivedSources/armv7 -I/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/DerivedSources -F/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Products/Debug-iphoneos -include /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/PrecompiledHeaders/mpesaCustomer-Prefix-dxzmkuigmvorbtaysqymjgwxgdqm/mpesaCustomer-Prefix.pch -MMD -MT dependencies -MF /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/Objects-normal/armv7/CDVDevice.d --serialize-diagnostics /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/Objects-normal/armv7/CDVDevice.dia -c /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/mpesaCustomer/Plugins/cordova-plugin-device/CDVDevice.m -o /Users/mac358818/vodafoneMpesaCustomer/platforms/ios/DerivedData/mpesaCustomer/Build/Intermediates/mpesaCustomer.build/Debug-iphoneos/mpesaCustomer.build/Objects-normal/armv7/CDVDevice.o

clang: error: no such file or directory: '/Users/mac358818/vodafoneMpesaCustomer/platforms/ios/mpesaCustomer/Plugins/cordova-plugin-device/CDVDevice.m'
clang: error: no input files
Command /Applications/Xcode 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by tbago** [comment]
not my project issus,wrong place.
